param(
    [ValidateSet("menu", "deepseek", "openai", "show")]
    [string]$Action = "menu",

    [string]$DefaultCCSBaseUrl = "http://127.0.0.1:3000/v1",
    [string]$DefaultDeepSeekModel = "deepseek-v4-pro",
    [string]$DefaultOpenAIModel = "gpt-5.5"
)

try {
    [Console]::InputEncoding = [System.Text.Encoding]::UTF8
    [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)
    $OutputEncoding = [System.Text.UTF8Encoding]::new($false)
} catch {}

function Read-WithDefault {
    param([string]$Prompt, [string]$DefaultValue)
    $text = Read-Host "$Prompt [$DefaultValue]"
    if ([string]::IsNullOrWhiteSpace($text)) { return $DefaultValue }
    return $text.Trim()
}

function Get-CodexPaths {
    $codexDir = Join-Path $HOME ".codex"
    $config = Join-Path $codexDir "config.toml"
    New-Item -ItemType Directory -Force -Path $codexDir | Out-Null
    return @{ Dir = $codexDir; Config = $config }
}

function Backup-Config {
    param([string]$Config)
    if (Test-Path $Config) {
        $backup = "$Config.bak_$(Get-Date -Format 'yyyyMMdd-HHmmss')"
        Copy-Item $Config $backup
        Write-Host "已备份原配置到："
        Write-Host "  $backup"
    }
}

function Remove-InvalidOpenAIKey {
    $targets = @(
        [EnvironmentVariableTarget]::User,
        [EnvironmentVariableTarget]::Machine
    )

    foreach ($target in $targets) {
        try {
            $key = [Environment]::GetEnvironmentVariable("OPENAI_API_KEY", $target)
            if ($key -eq "123456") {
                [Environment]::SetEnvironmentVariable("OPENAI_API_KEY", $null, $target)
                Write-Host "已删除 $target 里的无效 OPENAI_API_KEY=123456。"
            }
        } catch {}
    }

    if ($env:OPENAI_API_KEY -eq "123456") {
        Remove-Item Env:\OPENAI_API_KEY -ErrorAction SilentlyContinue
        Write-Host "已删除当前会话里的无效 OPENAI_API_KEY=123456。"
    }
}

function Write-DeepSeekConfig {
    Write-Host ""
    Write-Host "=== 切换到 CCS DeepSeek ==="
    $paths = Get-CodexPaths
    Backup-Config $paths.Config

    $ccsBaseUrl = Read-WithDefault "请输入 CCS OpenAI 兼容地址" $DefaultCCSBaseUrl
    $deepseekModel = Read-WithDefault "请输入 CCS 里的 DeepSeek 模型名" $DefaultDeepSeekModel
    $openaiModel = Read-WithDefault "保留的官方 OpenAI 模型名" $DefaultOpenAIModel

    Write-Host ""
    Write-Host "如果你的 CCS 开启了 Proxy Access Key / 代理访问密钥，请输入。"
    Write-Host "如果没有开启，可以直接回车。"
    $existingKey = [Environment]::GetEnvironmentVariable("CCS_API_KEY", [EnvironmentVariableTarget]::User)
    if (-not [string]::IsNullOrWhiteSpace($existingKey)) {
        Write-Host "检测到已有 CCS_API_KEY。直接回车将继续使用原来的值。"
    }
    $ccsKey = Read-Host "CCS Proxy Access Key"
    if ([string]::IsNullOrWhiteSpace($ccsKey) -and -not [string]::IsNullOrWhiteSpace($existingKey)) {
        $ccsKey = $existingKey
    }

    $configText = @"
# Codex default provider: CCS DeepSeek
# Generated by Codex Provider Switcher

model_provider = "ccs_deepseek"
model = "$deepseekModel"

approval_policy = "on-request"
sandbox_mode = "workspace-write"

[model_providers.ccs_deepseek]
name = "CCS DeepSeek V4 Pro"
base_url = "$ccsBaseUrl"
env_key = "CCS_API_KEY"
wire_api = "responses"
stream_idle_timeout_ms = 300000
request_max_retries = 2
stream_max_retries = 2

[profiles.openai]
model_provider = "openai"
model = "$openaiModel"

[profiles.deepseek]
model_provider = "ccs_deepseek"
model = "$deepseekModel"
"@
    $configText | Set-Content -Path $paths.Config -Encoding UTF8

    if (-not [string]::IsNullOrWhiteSpace($ccsKey)) {
        [Environment]::SetEnvironmentVariable("CCS_API_KEY", $ccsKey.Trim(), [EnvironmentVariableTarget]::User)
        $env:CCS_API_KEY = $ccsKey.Trim()
        Write-Host "已保存 CCS_API_KEY 到用户环境变量。"
    } else {
        Write-Host "未设置 CCS_API_KEY。只有 CCS 未开启代理密钥校验时才可用。"
    }

    Write-Host ""
    Write-Host "正在测试 CCS /v1/models..."
    try {
        $headers = @{}
        if (-not [string]::IsNullOrWhiteSpace($env:CCS_API_KEY)) {
            $headers["Authorization"] = "Bearer $env:CCS_API_KEY"
        }
        Invoke-RestMethod -Uri "$ccsBaseUrl/models" -Headers $headers -Method Get | Out-Null
        Write-Host "CCS /v1/models 测试通过。"
    } catch {
        Write-Host "警告：CCS /v1/models 测试失败。"
        Write-Host "常见原因：CCS 未启动、端口不对、代理访问密钥不对，或未开启 OpenAI 兼容 /v1。"
    }

    Write-Host ""
    Write-Host "已切换到 CCS DeepSeek。请完全退出 Codex 桌面端后重新打开。"
    Write-Host "配置文件：$($paths.Config)"
}

function Write-OpenAIConfig {
    Write-Host ""
    Write-Host "=== 切换到 OpenAI 官方登录账户 ==="
    $paths = Get-CodexPaths
    Backup-Config $paths.Config

    $openaiModel = Read-WithDefault "请输入官方 OpenAI 模型名" $DefaultOpenAIModel
    $deepseekModel = Read-WithDefault "保留的 DeepSeek 模型名" $DefaultDeepSeekModel
    $ccsBaseUrl = Read-WithDefault "保留的 CCS OpenAI 兼容地址" $DefaultCCSBaseUrl

    $configText = @"
# Codex default provider: OpenAI official account login
# Generated by Codex Provider Switcher

model_provider = "openai"
model = "$openaiModel"

approval_policy = "on-request"
sandbox_mode = "workspace-write"

[model_providers.ccs_deepseek]
name = "CCS DeepSeek V4 Pro"
base_url = "$ccsBaseUrl"
env_key = "CCS_API_KEY"
wire_api = "responses"
stream_idle_timeout_ms = 300000
request_max_retries = 2
stream_max_retries = 2

[profiles.openai]
model_provider = "openai"
model = "$openaiModel"

[profiles.deepseek]
model_provider = "ccs_deepseek"
model = "$deepseekModel"
"@
    $configText | Set-Content -Path $paths.Config -Encoding UTF8

    Remove-InvalidOpenAIKey

    Write-Host ""
    Write-Host "已切换到 OpenAI 官方登录账户模式。"
    Write-Host "不会要求输入 OPENAI_API_KEY。"
    Write-Host "如果桌面端提示登录，请在 Codex 桌面端里登录 OpenAI 账号。"
    Write-Host "请完全退出 Codex 桌面端后重新打开。"
    Write-Host "配置文件：$($paths.Config)"
}

function Show-Config {
    $paths = Get-CodexPaths
    Write-Host ""
    Write-Host "当前 Codex 配置文件："
    Write-Host "  $($paths.Config)"
    Write-Host ""
    if (Test-Path $paths.Config) {
        Get-Content $paths.Config
    } else {
        Write-Host "配置文件不存在。"
    }
    Write-Host ""
    $ccsKey = [Environment]::GetEnvironmentVariable("CCS_API_KEY", [EnvironmentVariableTarget]::User)
    $openaiKey = [Environment]::GetEnvironmentVariable("OPENAI_API_KEY", [EnvironmentVariableTarget]::User)

    if ([string]::IsNullOrWhiteSpace($ccsKey)) {
        Write-Host "用户环境变量 CCS_API_KEY：未设置"
    } else {
        Write-Host "用户环境变量 CCS_API_KEY：已设置"
    }

    if ([string]::IsNullOrWhiteSpace($openaiKey)) {
        Write-Host "用户环境变量 OPENAI_API_KEY：未设置。OpenAI 官方通道将依赖桌面端登录账户。"
    } elseif ($openaiKey -eq "123456") {
        Write-Host "用户环境变量 OPENAI_API_KEY：123456，明显无效，建议删除。"
    } else {
        Write-Host "用户环境变量 OPENAI_API_KEY：已设置。注意：这可能覆盖登录账户行为。"
    }
}

function Show-Menu {
    Write-Host ""
    Write-Host "=============================================="
    Write-Host "  Codex 桌面端 Provider 切换工具"
    Write-Host "=============================================="
    Write-Host "1. 切换到 CCS DeepSeek"
    Write-Host "2. 切换到 OpenAI 官方登录账户"
    Write-Host "3. 查看当前配置"
    Write-Host "4. 退出"
    Write-Host ""
    $choice = Read-Host "请选择 1/2/3/4"
    switch ($choice) {
        "1" { Write-DeepSeekConfig }
        "2" { Write-OpenAIConfig }
        "3" { Show-Config }
        default { Write-Host "已退出。" }
    }
}

switch ($Action) {
    "deepseek" { Write-DeepSeekConfig }
    "openai" { Write-OpenAIConfig }
    "show" { Show-Config }
    default { Show-Menu }
}
